# Generated by Django 2.2.2 on 2019-06-13 22:27

from django.db import migrations, models
import work.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('title', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=work.models.image_folder)),
                ('slug', models.SlugField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default=None, max_length=200, null=True)),
                ('description_short', models.TextField(blank=True, default=None, max_length=200, null=True)),
                ('top', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работа',
            },
        ),
    ]
