# Generated by Django 2.2.2 on 2019-06-13 23:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20190614_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='description_short',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
