# Generated by Django 2.2.2 on 2019-07-06 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='description',
            new_name='message',
        ),
    ]
