# Generated by Django 2.2.2 on 2019-06-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleblog',
            name='sidebar',
            field=models.BooleanField(default=False),
        ),
    ]
