# Generated by Django 2.2.2 on 2019-06-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articleblog_sidebar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleblog',
            name='sidebar',
            field=models.BooleanField(default=True),
        ),
    ]
