# Generated by Django 2.2.2 on 2019-06-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190616_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleblog',
            name='sidebar',
            field=models.BooleanField(default=True),
        ),
    ]
