# Generated by Django 2.2.2 on 2019-06-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190616_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleblog',
            name='sidebar',
            field=models.BooleanField(default=False),
        ),
    ]
