# Generated by Django 2.2.2 on 2019-06-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190616_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleblog',
            name='date',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
