# Generated by Django 2.2.2 on 2019-06-16 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190616_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleblog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='articleblog',
            name='sidebar',
        ),
    ]
