# Generated by Django 2.2.2 on 2019-06-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_articleblog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleblog',
            name='sidebar',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
