# Generated by Django 2.2.2 on 2019-06-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190626_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleblog',
            name='com_ents',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
