# Generated by Django 2.2.2 on 2019-06-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_articleblog_com_ents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleblog',
            old_name='com_ents',
            new_name='commentari',
        ),
    ]
