# Generated by Django 2.2.2 on 2019-06-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMeinTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firsttitle', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('secondname', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
