# Generated by Django 2.2.2 on 2019-06-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicemeintitle',
            options={'verbose_name': 'Загоовок', 'verbose_name_plural': 'Заголовки'},
        ),
    ]
