# Generated by Django 2.2.2 on 2019-06-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20190609_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicemeintitle',
            old_name='secondname',
            new_name='secondtitle',
        ),
    ]
