# Generated by Django 2.2.2 on 2019-06-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20190609_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Сервис фото',
                'verbose_name_plural': 'Сервисы фото',
            },
        ),
    ]
