# Generated by Django 2.2.2 on 2019-06-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_serviceimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimg',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static'),
        ),
    ]
