# Generated by Django 2.2.2 on 2019-06-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20190611_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('description', models.TextField(blank=True, default=None, max_length=200, null=True)),
                ('icon', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Сервис_2',
                'verbose_name_plural': 'Сервисы_2',
            },
        ),
    ]
